### ISSUE TITLE
Introduce Iteration/Invocation as key concepts

### ISSUE THREAD

**Issue by smarr** [smarr/ReBench#68]
Currently, we only have the notion of data points.
It is used for instance to determine how often benchmarks should be executed.

However, this approach is problematic, because it can be equivalent with measuring until some property is fulfilled, which is problematic in terms of verifying some hypothesis.

Instead, the setup parameters for experiments should be complete and well defined.
For our work on VMs, this means we need to decide upfront on a number of Iterations and Invocations for our experiments and not simply measure until our data happens to show that we are for instance under a specific threshold for run-time overhead.

This means, we should abandon the number of data points as a criterion for execution.
Instead, we should use iteration and invocation.

*Iteration*: the number of times a benchmark is executed in the same VM invocation.
*Invocation*: the number of times a VM is started to run benchmarks.

Related: with increasing number of iterations, the performance of a VM can change because of dynamic compilation and adaptive optimization, as well as other influences.

These should be settable within a configuration, but also via command-line arguments. For instance as `--invocation=n` or `--iteration=n`.

For quick runs, we could simply say that `-q` is equivalent to `--invocation=1` or `--iteration=1`.

## Handling for Faulty Runs

The handling of faulty runs should also be reconsidered.
We want to record for each data point/measurement whether it belongs to a faulty run or not.
And we want to check whether the abort conditions still make sense with invocations and iterations in the mix.

## Tasks

- [x] remove concept of "number of data points" #82
- [x] add invocation/iteration to configuration format (schema) #82
- [x] command line options: add --invocation/--iteration, adapt --quick #87
- [ ] ~~record faultiness of data points?~~ (postpone to #88)
- [x] change data format, probably relegate time stamp to comment on invocation (it isn't usable data anyway), and add columns: invocation, iteration, failed #87

**Comment by smarr** [comment]
Completed with #87.
